# Generated by Django 5.2.12 on 2026-09-21 15:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEntrepot',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Contact de l’agence (optionnel)', max_length=30, null=True, verbose_name='Contact')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS (ex: 5.345317 pour Abidjan-Plateau)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS (ex: -4.024429 pour Abidjan-Plateau)', max_digits=9, null=True)),
                ('statut', models.BooleanField(default=True, help_text='Coché = Ouvert, décoché = Fermé', verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('client', 'Client')], default='caissier', max_length=20)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
                ('local_entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_entrepot_users', to='userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('client', 'Client')], default='caissier', max_length=20)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('local_entrepot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CreneauDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('local_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['jour', 'heure_ouverture'],
                'constraints': [models.UniqueConstraint(fields=('local_entrepot', 'jour'), name='uniq_creneau_local_jour')],
            },
        ),
    ]
